config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  root 'welcome#home'

  mount ActionCable.server => '/cable'

  resources :sessions, only: [:new, :create]

  resources :songs
  resources :playlists




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_and_belongs_to_many :songs
  validates_presence_of :name
end

app/models/song.rb
class Song < ApplicationRecord
  has_and_belongs_to_many :playlists
  validates_presence_of :title, :artist, :bpm
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.order(:name)
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :genre)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    cookies.signed[:username] = params[:session][:username]
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order(:artist)
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist, :bpm)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jukebox" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <!-- Font Awesome CDN -->
    <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Jukebox</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Add Playlist(s)", "/playlists/new"  %></li>
            <li><%= link_to "Login with instagram", "/#"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <!-- <div class="well sidebar-nav"> -->
            <!-- <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul> -->
          <!-- </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer class="container-fluid">
        <p>&copy; IzzyCode 2016</p>
      </footer>

    </div> <!-- /container -->

    <% if Rails.env.development? %>
      <%= console %>
    <% end %>

  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_for @playlist, :html => { :class => "form-horizontal playlist" } do |f| %>

  <% if @playlist.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @playlist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :genre, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :genre, :class => 'form-control' %>
    </div>
    <%=f.error_span(:genre) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                playlists_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/playlists/edit.html.erb
<%- model_class = Playlist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/playlists/index.html.erb
<% model_class = Playlist %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %> <i class="fa fa-sort"></i></th>
      <th><%= model_class.human_attribute_name(:genre) %> <i class="fa fa-sort"></i></th>
    </tr>
    </tr>
  </thead>
  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= link_to playlist.name, playlist_path(playlist) %></td>
        <td><%= playlist.genre %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>

function sortTable(f,n){
var rows = $('tbody  tr').get();

rows.sort(function(a, b) {

  var A = getVal(a);
  var B = getVal(b);

  if(A < B) {
    return -1*f;
  }
  if(A > B) {
    return 1*f;
  }
  return 0;
});

function getVal(elm){
  var v = $(elm).children('td').eq(n).text().toUpperCase();
  if($.isNumeric(v)){
    v = parseInt(v,10);
  }
  return v;
}

$.each(rows, function(index, row) {
  $('table').children('tbody').append(row);
});
}
var f_sl = 1;
var f_nm = 1;
$("thead tr th").click(function(){
  f_sl *= -1;
  var n = $(this).prevAll().length;
  sortTable(f_sl,n);
});
// $("thead tr th:last-child").click(function(){
//   f_nm *= -1;
//   var n = $(this).prevAll().length;
//   sortTable(f_nm,n);
// });

</script>

app/views/playlists/new.html.erb
<%- model_class = Playlist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/playlists/show.html.erb
<% model_class = Playlist %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @playlist.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genre) %>:</strong></dt>
  <dd><%= @playlist.genre %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              playlists_path, :class => 'btn btn-default'  %>

<%= render partial: 'songs/index', locals: {songs: @playlist.songs} %>

app/views/songs/_form.html.erb
<%= form_for @song, :html => { :class => "form-horizontal song" } do |f| %>

  <% if @song.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :artist, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :artist, :class => 'form-control' %>
    </div>
    <%=f.error_span(:artist) %>
  </div>
  <div class="form-group">
    <%= f.label :bpm, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :bpm, :class => 'form-control' %>
    </div>
    <%=f.error_span(:bpm) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                songs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/songs/_index.html.erb
<% model_class = Song %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<% songs = songs.order("title ASC") #sort incoming Playlist.songs %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %> <i class="fa fa-sort"></i></th>
      <th><%= model_class.human_attribute_name(:artist) %> <i class="fa fa-sort"></i></th>
      <th><%= model_class.human_attribute_name(:bpm) %> <i class="fa fa-sort"></i></th>
    </tr>
  </thead>
  <tbody>
    <% songs.each do |song| %>
      <tr>
        <td><%= link_to song.title,  song_path(song)%></td>
        <td><%= song.artist %></td>
        <td><%= song.bpm %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/edit.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/new.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/show.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @song.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:artist) %>:</strong></dt>
  <dd><%= @song.artist %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bpm) %>:</strong></dt>
  <dd><%= @song.bpm %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              songs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_song_path(@song), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              song_path(@song),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/_suggested_song.html.erb
<p>
  <b><%= username %></b>:
  <%= suggested_song %>
</p>

app/views/welcome/home.html.erb
<p>Signed in as @<%= cookies.signed[:username] %>.</p>

<div id='song-queue'></div>
<br/><br/>

<%= text_field_tag :body, '', id: 'suggested_song' %>